config/routes.rb
Mete::Application.routes.draw do

  get 'audits.json', to: redirect('api/v1/audits.json'), format: false

  get 'barcodes.json', to: redirect('api/v1/barcodes.json'), format: false
  get 'barcodes/new.json', to: redirect('api/v1/barcodes/new.json'), format: false
  get 'barcodes/:id.json', to: redirect('api/v1/barcodes/%{id}.json'), format: false

  get 'drinks.json', to: redirect('api/v1/drinks.json'), format: false
  get 'drinks/new.json', to: redirect('api/v1/drinks/new.json'), format: false
  get 'drinks/:id.json', to: redirect('api/v1/drinks/%{id}.json'), format: false

  get 'users.json', to: redirect('api/v1/users.json'), format: false
  get 'users/new.json', to: redirect('api/v1/users/new.json'), format: false
  get 'users/:id.json', to: redirect('api/v1/users/%{id}.json'), format: false

  get 'users/:id/deposit.json', to: redirect('api/v1/users/%{id}/deposit.json'), format: false
  get 'users/:id/payment.json', to: redirect('api/v1/users/%{id}/payment.json'), format: false
  get 'users/:id/buy.json', to: redirect('api/v1/users/%{id}/buy.json'), format: false
  post 'users/:id/buy.json', to: redirect('api/v2/users/%{id}/buy.json'), format: false
  get 'users/:id/buy_barcode.json', to: redirect('api/v1/users/%{id}/buy_barcode.json'), format: false

  get 'users/stats.json', to: redirect('api/v1/users/stats.json'), format: false

  resources :drinks
  resources :barcodes

  get 'audits' => 'audits#index'

  resources :users do
    resources :wrapped
    member do
      post 'deposit'
      post 'payment'
      post 'buy'
      post 'buy_barcode'
    end
    collection do
      get 'stats'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :audits
      resources :drinks
      resources :barcodes
      resources :users do
        member do
          get 'deposit'
          get 'payment'
          get 'buy'
          post 'buy_barcode'
        end
        collection do
          get 'stats'
        end
      end
    end
    
    namespace :v2 do
      resources :audits
      resources :drinks
      resources :barcodes
      resources :users do
        member do
          post 'deposit'
          post 'payment'
          post 'buy'
          post 'buy_barcode'
        end
        collection do
          get 'stats'
        end
      end
    end
  end

  root :to => 'users#index'

end

app/models/drink.rb
class Drink < ApplicationRecord
  scope :order_by_name_asc, -> {
    order(arel_table['name'].lower.asc)
  }

  validates :name, :bottle_size, :price, presence: true

  has_attached_file :logo, :styles => { :thumb => "100x100#", :medium => "640x640#" }, :default_style => :medium
  validates_attachment_content_type :logo, :content_type => %w(image/jpeg image/jpg image/png)
  before_post_process :normalize_filename
  after_initialize :set_defaults, unless: :persisted?

  def as_json(options = {})
    h = super(options)
    h["donation_recommendation"] = price # API compatibility
    h["logo_url"] = logo.url
    h
  end

  private

  def set_defaults
    self.price = 1.5
  end

  def normalize_filename
    extension = File.extname(logo_file_name).downcase
    self.logo.instance_write :file_name, "logo#{extension}"
  end

end

app/controllers/api/v1/drinks_controller.rb
class Api::V1::DrinksController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  # GET /drinks.json
  def index
    @drinks = Drink.order(active: :desc).order_by_name_asc
    render json: @drinks
  end

  # GET /drinks/1.json
  def show
    @drink = Drink.find(params[:id])
    render json: @drink
  end

  # GET /drinks/new.json
  def new
    @drink = Drink.new
    render json: @drink
  end

  # POST /drinks.json
  def create
    @drink = Drink.new(drink_params)
    if @drink.save
      render json: @drink, status: :created, location: @drink
    else
      render json: @drink.errors, status: :unprocessable_entity
    end
  end

  # PATCH /drinks/1.json
  def update
    @drink = Drink.find(params[:id])
    if @drink.update(drink_params)
      head :no_content
    else
      render json: @drink.errors, status: :unprocessable_entity
    end
  end

  # DELETE /drinks/1.json
  def destroy
    @drink = Drink.find(params[:id])
    Barcode.where(:drink => @drink.id).each do |barcode|
      barcode.destroy!
    end
    if @drink.destroy
      head :no_content
    else
      render json: @drink.errors, status: :unprocessable_entity
    end
  end

  private

  def drink_params
    params.require(:drink).permit(:bottle_size, :caffeine, :price, :logo, :name, :active)
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  # GET /drinks
  def index
    @drinks = Drink.order(active: :desc).order_by_name_asc
    # index.html.haml
  end

  # GET /drinks/1
  def show
    @drink = Drink.find(params[:id])
    # show.html.haml
  end

  # GET /drinks/new
  def new
    @drink = Drink.new
    # new.html.haml
  end

  # GET /drinks/1/edit
  def edit
    @drink = Drink.find(params[:id])
    # edit.html.haml
  end

  # POST /drinks
  def create
    @drink = Drink.new(drink_params)
    if @drink.save
      redirect_to @drink, :flash => { :success => 'Drink was successfully created.' }
    else
      render action: "new", error: "Couldn't create the drink. Error: #{@drink.errors} Status: #{:unprocessable_entity}"
    end
  end

  # PATCH /drinks/1
  def update
    @drink = Drink.find(params[:id])
    if @drink.update(drink_params)
      flash[:success] = "Drink was successfully updated."
      no_resp_redir @drink
    else
      render action: "edit", error: "Couldn't update the drink. Error: #{@drink.errors} Status: #{:unprocessable_entity}"
    end
  end

  # DELETE /drinks/1
  def destroy
    @drink = Drink.find(params[:id])
    Barcode.where(:drink => @drink.id).each do |barcode|
      barcode.destroy!
      flash[:info] = "Deleted all barcodes for this drink."
    end
    if @drink.destroy
      flash[:success] = "Drink was successfully deleted."
      no_resp_redir drinks_url
    else
      redirect_to drinks_url, :flash => { :error => "Couldn't delete the drink. Error: #{@drink.errors} Status: #{:unprocessable_entity}" }
    end
  end

  private

  def drink_params
    params.require(:drink).permit(:bottle_size, :caffeine, :price, :logo, :name, :active)
  end
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/_drink.html.haml
- path = buy_user_path(@user, :drink => drink.id) if @user

.col-12.col-sm-4.col-md-3.col-lg-2.col-xl-2.my-2
  = link_to(path || '#', data: drink.active? ? {} : {confirm: "This drink is inactive. Do you really want to buy #{drink.name}?"}, method: :post) do
    .card.drink-card.text-center
      .card-header
        .inner-header
          %h6= drink.name
      .card-body
        = image_tag drink.logo(:medium), alt: drink.name, class: drink.active? ? "" : "disabled", size: 100
      .card-footer
        = show_amount drink.price
        %br
        - if drink.bottle_size?
          = sprintf('%.2f', drink.price / drink.bottle_size)
          €/L
        - else
          
        %br
        - if drink.caffeine && !drink.caffeine.zero? && drink.bottle_size && !drink.bottle_size.zero?
          = sprintf('%.2f', (drink.caffeine * (drink.bottle_size / 0.1) / drink.price))
          mg caffeine/€
        - else
          no caffeine

app/views/drinks/_form.html.haml
- content_for :actions do
  %li
    = link_to 'delete drink', @drink, method: :delete, :data => {confirm: "Really delete drink #{@drink.name}?"}

= simple_form_for @drink, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, hint:'the label says…'
    = f.input :price, as: :decimal
    = f.input :bottle_size, hint: '0.5 or 0.33?'
    = f.input :caffeine, hint: 'in mg/100 ml'
    = f.input :logo, hint: 'make it look pretty'
    = f.input :active
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to 'Add a barcode', new_barcode_path(:drink => @drink.id), :class => 'btn'

app/views/drinks/edit.html.haml
- model_class = Drink
- content_for :title do
  Edit drink
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/drinks/index.html.haml
- model_class = Drink
- content_for :title do
  Drinks
- content_for :actions do
  %li.nav-item
    = link_to 'new drink', [:new, :drink], class: "nav-link"

.page-header
  %h1
    Drinks.
    %small All of them!

%table.table.table-striped.table-bordered.table-dark
  %thead
    %tr
      %th{:scope => "col"}
        = model_class.human_attribute_name(:logo)
        %span.small
          (click to edit drink)
      %th{:scope => "col"}= model_class.human_attribute_name(:name)
      %th{:scope => "col"}= model_class.human_attribute_name(:bottle_size)
      %th{:scope => "col"}= model_class.human_attribute_name(:caffeine)
      %th{:scope => "col"}= model_class.human_attribute_name(:price)
      %th{:scope => "col"}= model_class.human_attribute_name(:created_at)
  %tbody
    - @drinks.each do |drink|
      %tr
        %td
          = link_to [:edit, drink] do
            = image_tag drink.logo(:medium), class: drink.active ? "" : "disabled", size: 100
        %th{:scope => "row"}= drink.name
        %td= drink.bottle_size
        %td= drink.caffeine
        %td= show_amount drink.price
        %td= drink.created_at.strftime("%d %b %Y - %H:%M")

app/views/drinks/new.html.haml
- content_for :title do
  Add drink
.page-header
  %h1
    New Drink
    %small for new ideas
= render :partial => "form"

app/views/drinks/show.html.haml
= render @drink
- content_for :title do
  Drink

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), drinks_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_drink_path(@drink), :class => 'btn'
  = link_to 'Add barcode', new_barcode_path(:drink => @drink.id), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), drink_path(@drink), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'