config/routes.rb
Mete::Application.routes.draw do

  get 'audits.json', to: redirect('api/v1/audits.json'), format: false

  get 'barcodes.json', to: redirect('api/v1/barcodes.json'), format: false
  get 'barcodes/new.json', to: redirect('api/v1/barcodes/new.json'), format: false
  get 'barcodes/:id.json', to: redirect('api/v1/barcodes/%{id}.json'), format: false

  get 'drinks.json', to: redirect('api/v1/drinks.json'), format: false
  get 'drinks/new.json', to: redirect('api/v1/drinks/new.json'), format: false
  get 'drinks/:id.json', to: redirect('api/v1/drinks/%{id}.json'), format: false

  get 'users.json', to: redirect('api/v1/users.json'), format: false
  get 'users/new.json', to: redirect('api/v1/users/new.json'), format: false
  get 'users/:id.json', to: redirect('api/v1/users/%{id}.json'), format: false

  get 'users/:id/deposit.json', to: redirect('api/v1/users/%{id}/deposit.json'), format: false
  get 'users/:id/payment.json', to: redirect('api/v1/users/%{id}/payment.json'), format: false
  get 'users/:id/buy.json', to: redirect('api/v1/users/%{id}/buy.json'), format: false
  post 'users/:id/buy.json', to: redirect('api/v2/users/%{id}/buy.json'), format: false
  get 'users/:id/buy_barcode.json', to: redirect('api/v1/users/%{id}/buy_barcode.json'), format: false

  get 'users/stats.json', to: redirect('api/v1/users/stats.json'), format: false

  resources :drinks
  resources :barcodes

  get 'audits' => 'audits#index'

  resources :users do
    resources :wrapped
    member do
      post 'deposit'
      post 'payment'
      post 'buy'
      post 'buy_barcode'
    end
    collection do
      get 'stats'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :audits
      resources :drinks
      resources :barcodes
      resources :users do
        member do
          get 'deposit'
          get 'payment'
          get 'buy'
          post 'buy_barcode'
        end
        collection do
          get 'stats'
        end
      end
    end
    
    namespace :v2 do
      resources :audits
      resources :drinks
      resources :barcodes
      resources :users do
        member do
          post 'deposit'
          post 'payment'
          post 'buy'
          post 'buy_barcode'
        end
        collection do
          get 'stats'
        end
      end
    end
  end

  root :to => 'users#index'

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :name, presence: true

  enum :avatar_provider, [ :gravatar, :webfinger ]

  scope :order_by_name_asc, -> {
    order(arel_table['name'].lower.asc)
  }

  after_save do |user|
    Audit.create! difference: user.balance - user.balance_before_last_save, drink: @purchased_drink, user: user.audit? ? user : nil
  end

  def deposit(amount)
    with_lock do
      self.balance += amount
      save!
    end
  end

  def buy(drink)
    with_lock do
      self.balance -= drink.price
      @purchased_drink = drink
      save!
    end
  end

  def payment(amount)
    with_lock do
      self.balance -= amount
      save!
    end
  end

  def initial
    first = name[0, 1].downcase
    return first if first =~ /[a-z]/
    '0'
  end

  def email
    case avatar_provider
    when 'gravatar'
      avatar
    when 'webfinger'
      ''
    end
  end

  def as_json(options={})
    super(except: [ :avatar_provider, :avatar ], methods: :email)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /users.json
  def index
    @users = User.order(active: :desc).order_by_name_asc
    render json: @users
  end

  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @drinks = Drink.order(active: :desc).order_by_name_asc
    render json: @user
  end

  # GET /users/new.json
  def new
    @user = User.new
    render json: @user
  end

  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH /users/1
  # PATCH /users/1.json
  def update
    @user = User.find(params[:id])
    @old_audit_status = @user.audit
    if @user.update(user_params)
      if @user.audit != @old_audit_status
        unless @user.audit
          @user_audits = Audit.where(:user => @user.id)
          @user_audits.each do |audit|
            audit.user = nil
            audit.save!
          end
        end
      end
      head :no_content
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      head :no_content
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # GET /users/1/deposit.json?amount=100
  def deposit
    @user = User.find(params[:id])
    @user.deposit(BigDecimal(params[:amount]))
    head :no_content
  end

  # GET /users/1/buy.json?drink=5
  def buy
    @user = User.find(params[:id])
    @drink = Drink.find(params[:drink])
    buy_drink
  end

  # POST /users/1/buy_barcode.json
  def buy_barcode
    @user = User.find(params[:id])
    unless Barcode.where(id: params[:barcode]).exists?
      render json: @user.errors, status: :unprocessable_entity
    else
      @drink = Drink.find(Barcode.find(params[:barcode]).drink)
      buy_drink
    end
  end

  # GET /users/1/pay.json?amount=1.5
  def payment
    @user = User.find(params[:id])
    @user.payment(BigDecimal(params[:amount]))
    head :no_content
  end

  # GET /users/stats.json
  def stats
    @user_count = User.count
    @balance_sum = User.sum(:balance)
    render json: { user_count: @user_count, balance_sum: @balance_sum }
  end

  private

  def buy_drink
    unless @drink.active?
      @drink.active = true
      @drink.save!
    end
    @user.buy(@drink)
    head :no_content
  end

  def user_params
    email = params[:email]
    input = params.require(:user).permit(:name, :balance, :active, :audit, :redirect)

    if email
      input[:avatar_provider] = 'gravatar'
      input[:avatar] = email
    end

    input
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  include UsersHelper

  # GET /users
  def index
    @users = User.order(active: :desc).order_by_name_asc
    # index.html.haml
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
    @drinks = Drink.order(active: :desc).order(caffeine: :asc).order_by_name_asc
    @wrapped = nil
    if @user.audit
      if Date.today.month == 12
        @wrapped = Date.today.year
      end
      if Date.today.month == 01
        @wrapped = Date.today.year - 1
      end
    end
    # show.html.haml
  end

  # GET /users/new
  def new
    @user = User.new
    # new.html.haml
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    # edit.html.haml
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, :flash => { :success => 'User was successfully created.' }
    else
      render action: "new", error: "Couldn't create the user. Error: #{@user.errors} Status: #{:unprocessable_entity}"
    end
  end

  # PATCH /users/1
  def update
    @user = User.find(params[:id])
    @old_audit_status = @user.audit
    if @user.update(user_params)
      if @user.audit != @old_audit_status
        unless @user.audit
          @user_audits = Audit.where(:user => @user.id)
          @user_audits.each do |audit|
            audit.user = nil
            audit.save!
          end
          flash[:info] = "Deleted all your logs."
        end
      end

      if @user.avatar_provider = "webfinger"
        Rails.cache.delete "fetch_avatar_url_from_webfinger_or_activitypub #{@user.avatar}"
      end

      flash[:success] = "User was successfully updated."
      no_resp_redir @user
    else
      render action: "edit", error: "Couldn't update the user. Error: #{@user.errors} Status: #{:unprocessable_entity}"
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "User was successfully deleted."
      no_resp_redir users_url
    else
      redirect_to users_url, :flash => { :error => "Couldn't delete the user. Error: #{@user.errors} Status: #{:unprocessable_entity}" }
    end
  end

  # GET /users/1/deposit?amount=100
  def deposit
    @user = User.find(params[:id])
    @user.deposit(BigDecimal(params[:amount]))
    flash[:success] = "You just deposited some money and your new balance is #{show_amount(@user.balance)}. Thank you."
    warn_user_if_audit
    no_resp_redir @user
  end

  # GET /users/1/buy?drink=5
  def buy
    @user = User.find(params[:id])
    @drink = Drink.find(params[:drink])
    buy_drink
  end

  # POST /users/1/buy_barcode
  def buy_barcode
    @user = User.find(params[:id])
    unless Barcode.where(id: params[:barcode]).exists?
      flash[:danger] = "No drink found with this barcode."
      redirect_to @user
    else
      @drink = Drink.find(Barcode.find(params[:barcode]).drink)
      buy_drink
    end
  end

  # GET /users/1/pay?amount=1.5
  def payment
    @user = User.find(params[:id])
    @user.payment(BigDecimal(params[:amount]))
    print_balance
    warn_user_if_audit
    no_resp_redir @user
  end

  # GET /users/stats
  def stats
    @user_count = User.count
    @balance_sum = User.sum(:balance)
    # stats.html.haml
  end

  private

  def buy_drink
    @user.buy(@drink)
    print_balance
    warn_user_if_audit
    no_resp_redir @user.redirect ? redirect_path(@user) : @user
  end

  def user_params
    params.require(:user).permit(:name, :avatar_provider, :avatar, :balance, :active, :audit, :redirect)
  end

  def warn_user_if_audit
    if (@user.audit) then
      flash[:info] = "This transaction has been logged, because you set up your account that way. #{view_context.link_to 'Change?', edit_user_url(@user)}".html_safe
    end
  end
  
  def print_balance
    flash[:success] = "You just bought a drink and your new balance is #{show_amount(@user.balance)}. Thank you."
    if (@user.balance < -50) then
      flash[:danger] = "Your balance is way below zero. Remember to compensate as soon as possible."
    elsif (@user.balance < 0) then
      flash[:warning] = "Your balance is below zero. Please remember to compensate."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # see also: /config/initializers/gravatar_image_tag.rb
  
  def avatar(user)
    case user.avatar_provider
    when 'gravatar'
      if user.avatar.nil? or user.avatar.empty? then
        content_tag :div, nil, class: [ 'avatar-missing' ]
      else 
        gravatar_image_tag user.avatar, class: user.active? ? '' : 'disabled'
      end
    when 'webfinger'
      webfinger_activitypub_image_tag user.avatar
    end
  end

  def redirect_path(user)
    return users_path + '/#' + user.initial
  end

  private

  def http_client
    Faraday.new Mete::Application.config.avatar_mastodon_client_url do |faraday|
      faraday.headers[:user_agent] = "Metekasse (#{Faraday::Connection::USER_AGENT})"
      faraday.response :json
      faraday.response :follow_redirects
      faraday.adapter Faraday.default_adapter
    end
  end

  # NOTE: This function attempts to retrieve an avatar url by directly
  #       talking ActivityPub to an endpoint discovered by Webfinger.
  #       This will fail in case servers require signed requests.
  def fetch_avatar_url_from_activitypub_server(activity_json_url)
    activity_json_response = http_client.get(activity_json_url) do |request|
      request.headers[:accept] = 'application/activity+json'
    end

    Rails.logger.debug "Using activity+json '#{activity_json_url}' fetched directly, resolving to '#{activity_json_response.body.dig('icon', 'url')}'"

    activity_json_response.body.dig('icon', 'url')
  end

  # NOTE: This function attempts to retrieve an avatar url by talking to a Mastodon
  #       server and looking up an account. This request will optionally include
  #       authentication against the Mastodon API.
  def fetch_avatar_url_using_mastodon_client(subject)
    http_client.url_prefix = Mete::Application.config.avatar_mastodon_client_url

    mastodon_response = http_client.get('/api/v1/accounts/lookup') do |request|
      request.params[:acct] = subject.delete_prefix('acct:')
      request.headers[:authorization] = "Bearer #{Mete::Application.config.avatar_mastodon_client_token}"
    end

    Rails.logger.debug "Using subject '#{subject}' fetched via Mastodon API on #{Mete::Application.config.avatar_mastodon_client_url}, resolving to '#{mastodon_response.body.dig('avatar')}'"

    mastodon_response.body.dig('avatar')
  end

  def fetch_avatar_url_from_webfinger_or_activitypub(identifier)
    # NOTE: The WebFinger gem supports identifiers like "gnom.is" without a "user@",
    #       allowing the somewhat common practice of serving a static webfinger file.
    #       It does however not support something like "@ordnung@chaos.social", only
    #       "ordnung@chaos.social", as such we trim an initial "@" here.
    webfinger_response = WebFinger.discover! identifier.delete_prefix('@') rescue return

    return unless webfinger_response.is_a? Hash

    webfinger_subject = webfinger_response[:subject]
    webfinger_links = webfinger_response[:links]

    return unless webfinger_subject.is_a? String
    return unless webfinger_links.is_a? Enumerable

    # NOTE: This is a standard relation that not much fediverse software seems to implement currently.
    #       Since first working on this Mete feature, Mastodon 4.2.0 and newer now have support!
    webfinger_avatar_relation = webfinger_links.find do |entry|
      entry.is_a?(Hash) &&
        entry[:rel] == 'http://webfinger.net/rel/avatar' &&
        entry[:href].is_a?(String)
    end

    activity_json_relation = webfinger_links.find do |entry|
      entry.is_a?(Hash) &&
        entry[:rel] == 'self' &&
        entry[:type] == 'application/activity+json' &&
        entry[:href].is_a?(String)
    end

    Rails.logger.debug "Resolved identifier '#{identifier}' with webfinger to subject '#{webfinger_subject}', avatar relation '#{webfinger_avatar_relation&.fetch(:href)}' and self activity+json relation '#{activity_json_relation&.fetch(:href)}'"

    if webfinger_avatar_relation
      Rails.logger.debug "Using http://webfinger.net/rel/avatar '#{webfinger_avatar_relation[:href]}'"
      webfinger_avatar_relation[:href]
    elsif Mete::Application.config.avatar_mastodon_client_url
      fetch_avatar_url_using_mastodon_client webfinger_subject rescue return
    else
      fetch_avatar_url_from_activitypub_server activity_json_relation[:href] rescue return
    end
  end

  def webfinger_activitypub_image_tag(identifier)
    avatar_url = Rails.cache.fetch("fetch_avatar_url_from_webfinger_or_activitypub #{identifier}", expires_in: 1.day) do
      fetch_avatar_url_from_webfinger_or_activitypub identifier
    end

    if not avatar_url
      return content_tag :div, nil, class: [ 'avatar-missing' ]
    end

    options = {}
    options[:src] = avatar_url
    options[:alt] = "Profile picture for #{identifier}"
    options[:height] = options[:width] = 80
    tag :img, options, false, false
  end
end

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, hint: 'your nickname'
    = f.input :avatar_provider,
      :collection => [['Gravatar', 'gravatar'], ['WebFinger / ActivityPub', 'webfinger']],
      :as => :radio_buttons,
      :hint => "This determines how the identifier below will be interpreted. Use an email for Gravatar and a fediverse username for WebFinger / ActivityPub"
    = f.input :avatar, hint: 'An identifier for your avatar'
    = f.input :balance, :as => :decimal, hint: 'just in case you need to correct this'
    = f.input :active
    = f.input :audit, hint: 'This will create detailed logs about what you buy and deposit. If you uncheck this box, all records will be deleted.'
    = f.input :redirect, hint: "Redirect after buying a drink?"
  .form-actions
    = f.button :submit, class: 'btn-primary'

%style .user { display: initial!important; }

app/views/users/_transfer_form.html.haml
= semantic_form_for :transfer, :html => { :class => 'form-horizontal' } do |f|
  = f.inputs do
    = f.input :amount, :as => :number, hint: 'what do amount do you want to transfer?'
    = f.input :destination, :as => :select, :collection => @users, hint: 'who gets the money?'
  = f.actions do
    = f.action :submit

app/views/users/_user.html.haml
.col-6.col-sm-4.col-md-3.col-lg-2.col-xl-2.my-2.user{class: "user-#{user.initial}"}
  = link_to user, :title => user.name do
    .card.user-card.text-center
      .card-header
        .inner-header
          %h6= user.name
      .card-body
        = avatar(user)

app/views/users/edit.html.haml
- model_class = User
- content_for :title do
  Edit user
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
- content_for :title do
  Tap-In
- content_for :actions do
  %li.nav-item
    = link_to 'new user', [:new, :user], class: "nav-link"

.user-filter
  .btn-group
    %a.btn{href: "#0", class: "user-filter-0"} #
    - ('a'..'z').each do |a|
      %a.btn{href: "##{a}", class: "user-filter-#{a}"}= a
.row
.row
  = render @users

- content_for :footer do
  = javascript_include_tag "users"
  %noscript
    %style .user { display: initial; }
    %style .user-filter { display: none; }

app/views/users/new.html.haml
- content_for :title do
  Add user
.page-header
  %h1
    Welcome, fellow hacker
    %small join the party!
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
- content_for :title do
  User #{@user.name}
- content_for :actions do
  %li.nav-item
    = link_to 'edit user', edit_user_path(@user), class: "nav-link"
  - if @user.audit?
    %li.nav-item
      = link_to 'show logs', audits_path(:user => @user), class: "nav-link"
  %li.nav-item
    = link_to 'delete user', @user, :method => :delete, :data => {:confirm => "Really delete #{@user.name}’s account?"}, class: "nav-link"
.page-header
  %h1
    = "Hi, #{@user.name}"
    %small
      Pick Your Poison.

.row
  .col-4.col-sm-3.col-md-2.col-lg-2.col-xl-1#user-page-avatar-holder
    = avatar(@user)
  .col-8.col-sm-9.col-md-10.col-lg-10.col-xl-11
    %dl.dl-horizontal
      %dt
        = @user.avatar_provider == "gravatar" ? "Gravatar" : "WebFinger / ActivityPub"
      %dd
        = @user.avatar
      %dt
        = model_class.human_attribute_name(:balance)
      %dd
        - if @user.balance < -50
          .text-danger
            = show_amount @user.balance
        - elsif @user.balance < 0
          .text-warning
            = show_amount @user.balance
        - else
          .text-success
            = show_amount @user.balance

- if @wrapped
  .mt-3.alert.alert-info
    Your #{@wrapped} wrapped is available.
    = link_to 'See what you\'ve been up to.', user_wrapped_path(@user, @wrapped)

%hr

%form{:method => "POST", :action => buy_barcode_user_path}
  %small
    Buy a drink by scanning a barcode: 
  = hidden_field_tag :authenticity_token, form_authenticity_token
  %input{:name => "barcode", :autofocus => ""}

%hr

.row.drinks
  = render @drinks, :locals => {:user => @user}

.row
  = render partial: 'bills'

app/views/users/stats.html.haml
- model_class = User
- content_for :title do
  Stats
%ul
  %li User count: #{@user_count}
  %li Balance sum: #{show_amount @balance_sum}

app/views/users/transfer.html.haml
- model_class = User
.page-header
  %h1
    Transfer an amount
= render :partial => "transfer_form"